# Generated by Django 2.2.3 on 2019-07-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20190706_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedoctor',
            name='catname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.Free_category'),
        ),
    ]
