# Generated by Django 2.2.3 on 2019-07-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20190706_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='clinic_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
