# Generated by Django 2.2.3 on 2019-07-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20190706_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedoctor',
            name='catname',
        ),
        migrations.RemoveField(
            model_name='freedoctor',
            name='username',
        ),
        migrations.DeleteModel(
            name='Free_category',
        ),
        migrations.DeleteModel(
            name='FreeDoctor',
        ),
    ]
