# Generated by Django 2.2.3 on 2019-08-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20190718_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='clinic_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
